adb shell "cmd package resolve-activity --brief com.android.dialer | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.documentsui | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.gallery3d | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.keychain | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.messaging | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.mtp | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.nfc | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.providers.calendar | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.providers.downloads | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.providers.media | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.vending | tail -n 1"
adb shell "cmd package resolve-activity --brief com.cyanogenmod.lockclock | tail -n 1"
adb shell "cmd package resolve-activity --brief com.cyanogenmod.settings.device | tail -n 1"
adb shell "cmd package resolve-activity --brief com.cyanogenmod.trebuchet | tail -n 1"
adb shell "cmd package resolve-activity --brief org.cyanogenmod.audiofx | tail -n 1"
adb shell "cmd package resolve-activity --brief org.cyanogenmod.snap | tail -n 1"
pause