@echo off
title LAUNCHABLE ACTIVITY NAME
adb shell "cmd package resolve-activity --brief com.android.dialer | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.documentsui | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.gallery3d | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.messaging | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.vending | tail -n 1"
adb shell "cmd package resolve-activity --brief org.cyanogenmod.audiofx | tail -n 1"
adb shell "cmd package resolve-activity --brief org.cyanogenmod.snap | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.chrome | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.contacts | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.phone | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.providers.settings | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.providers.downloads.ui | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.settings | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.providers.telephony | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.storagemanager | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.systemui | tail -n 1"
adb shell "cmd package resolve-activity --brief com.android.terminal | tail -n 1"
adb shell "cmd package resolve-activity --brief com.cyanogenmod.eleven | tail -n 1"
adb shell "cmd package resolve-activity --brief com.discord | tail -n 1"
adb shell "cmd package resolve-activity --brief com.google.android.apps.inbox | tail -n 1"
adb shell "cmd package resolve-activity --brief com.nolanlawson.logcat | tail -n 1"
adb shell "cmd package resolve-activity --brief com.speedsoftware.rootexplorer | tail -n 1"
adb shell "cmd package resolve-activity --brief com.xda.labs | tail -n 1"
adb shell "cmd package resolve-activity --brief eu.chainfire.supersu | tail -n 1"
adb shell "cmd package resolve-activity --brief org.lineageos.recorder | tail -n 1"
adb shell "cmd package resolve-activity --brief org.telegram.messenger | tail -n 1"
adb shell "cmd package resolve-activity --brief com.facebook.katana | tail -n 1"
adb shell "cmd package resolve-activity --brief com.dv.adm.pay | tail -n 1"
pause